name: Publish Beta
env:
  VERSION: 3.1.0
  NODE_VERSION: '18.18.2'

on:
  push:
    tags:
      - "*beta*"

jobs:
  publish:
    name: Publish on NPM.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: 'https://registry.npmjs.org'
      - name: Install yarn
        shell: bash
        run: corepack enable
      - name: Install ts-node
        shell: bash
        run: npm install -g ts-node
      - name: Publish to NPM
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
